### ISSUE TITLE
翻訳を開始したらすぐに翻訳状況コンポーネントに表示されるようにしたい

### ISSUE THREAD

**Issue by ttizze** [ttizze/eveeve#106]
why
現在登録されるまでに間が空いていてUXがよくない

**Comment by coji** [comment]
思いました。最初にURLを fetch してくるところですよね。

翻訳のステータスを追加して、翻訳がリクエストされたらすぐに同期的にレコードを作成した上で、翻訳処理をバックグラウンドで行えばいいのかなと思うのですが、認識あってるでしょうか。

**Comment by ttizze** [comment]
ありがとうございます｡
認識相違ないです!

> 翻訳のステータスを追加して、翻訳がリクエストされたらすぐに同期的にレコードを作成
ですね､以下の

pageId
pageVersionId
UserAITranslationInfo

を作成すれば翻訳状況コンポーネントに表示されるはずです!
よろしくお願いします!

**Comment by ttizze** [comment]
自動でブランチ切られるのですが、forkで作業されているので、このブランチは気にしないでもらって大丈夫です🙆
